name: vulncheck
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas=2.0.3
  - numpy
  - plotly=5.18.0
  - dash=2.14.2
  - dash-bootstrap-components=1.5.0
  - flask=3.0.0
  - requests=2.31.0
  - python-dotenv=1.0.0
  - pytest=7.4.0
  - pip
